import React, { SetStateAction, useState } from "react";
import { cn } from "@/lib/utils";
import 'animate.css';
import "@/styles/globals.css";
import "@/styles/dark-mode.css"
import "@/styles/glassomorphic.css";
import "@/styles/patterns.css";
import "@/styles/sacred-geometry.scss";
import "@/styles/inter.css"

// import { GeistSans } from "geist/font/sans";
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/providers/theme-provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const useClasses = false;
  // const classes = useClasses ? "grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]" : "min-h-screen w-full";


  return (
    <html lang="en" className={inter.variable}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
