import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import "@/styles/glassomorphic.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const useClasses = false;
  const classes = useClasses ? "grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]" : "min-h-screen w-full";
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className={cn(classes)}>
          {children}
        </div>
      </body>
    </html>
  );
}
